(() => {
  const DB='bali-mobile-admin-offline-v1', VER=1, SNAP='baliMobileAdminSnapshotV1';
  let saveTimer=0;
  function openDb(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB,VER);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains('media'))db.createObjectStore('media',{keyPath:'path'});if(!db.objectStoreNames.contains('pending'))db.createObjectStore('pending',{keyPath:'path'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
  async function get(store,key){const db=await openDb();try{return await new Promise((resolve,reject)=>{const tx=db.transaction(store,'readonly'),r=tx.objectStore(store).get(key);r.onsuccess=()=>resolve(r.result||null);r.onerror=()=>reject(r.error)})}finally{db.close()}}
  async function putDb(store,value){const db=await openDb();try{await new Promise((resolve,reject)=>{const tx=db.transaction(store,'readwrite');tx.objectStore(store).put(value);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}finally{db.close()}}
  async function delDb(store,key){const db=await openDb();try{await new Promise((resolve,reject)=>{const tx=db.transaction(store,'readwrite');tx.objectStore(store).delete(key);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}finally{db.close()}}
  async function allDb(store){const db=await openDb();try{return await new Promise((resolve,reject)=>{const tx=db.transaction(store,'readonly'),r=tx.objectStore(store).getAll();r.onsuccess=()=>resolve(r.result||[]);r.onerror=()=>reject(r.error)})}finally{db.close()}}
  const b64Blob=(b64,mime='image/jpeg')=>{const bin=atob(String(b64||'').replace(/\n/g,'')),a=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)a[i]=bin.charCodeAt(i);return new Blob([a],{type:mime})};
  const mimeFor=p=>/\.png$/i.test(p)?'image/png':/\.webp$/i.test(p)?'image/webp':'image/jpeg';
  function saveSnapshotNow(){try{localStorage.setItem(SNAP,JSON.stringify({manifest,cocktails,ingredients,products,dirty,savedAt:Date.now()}))}catch{}}
  function scheduleSnapshot(){clearTimeout(saveTimer);saveTimer=setTimeout(saveSnapshotNow,80)}
  async function restorePending(){try{for(const row of await allDb('pending'))if(row?.path&&row?.b64)pending.set(row.path,row.b64)}catch{}}
  function loadSnapshot(){try{const x=JSON.parse(localStorage.getItem(SNAP)||'null');if(!x||!Array.isArray(x.cocktails))return false;manifest=x.manifest||{};cocktails=x.cocktails||[];ingredients=x.ingredients||[];products=x.products||[];dirty=Boolean(x.dirty);cocktails.sort(alpha);ingredients.sort(alpha);products.sort(alpha);renderAll();if($('version'))$('version').textContent=`Каталог v${manifest.catalogVersion||0} · офлайн`;if(dirty){$('dirty').textContent='Есть локальные неопубликованные изменения';$('dirty').classList.add('on')}else clean();restorePending().catch(()=>{});return true}catch{return false}}
  window.BALI_mobileAdminLoadSnapshot=loadSnapshot;
  async function refreshMedia(path){const r=await fetch(RAW+path+'?v='+(manifest?.catalogVersion||0)+'&ts='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('media '+r.status);const blob=await r.blob();await putDb('media',{path,blob,version:Number(manifest?.catalogVersion||0),savedAt:Date.now()});return blob}
  async function fetchMedia(path){if(!path)return null;const cached=await get('media',path).catch(()=>null);if(cached?.blob){if(navigator.onLine)setTimeout(()=>refreshMedia(path).catch(()=>{}),0);return cached.blob}if(!navigator.onLine)return null;return refreshMedia(path)}
  async function hydrate(id,path){const img=$(id);if(!img||!path)return;try{const blob=await fetchMedia(path);if(blob)img.src=URL.createObjectURL(blob)}catch{}}
  async function cacheAllMedia(){if(!navigator.onLine)return 0;const paths=[...new Set([...(cocktails||[]).map(x=>x.officialImage),...(ingredients||[]).map(x=>x.officialImage)].filter(Boolean))];let n=0;for(let i=0;i<paths.length;i+=4){await Promise.allSettled(paths.slice(i,i+4).map(async p=>{const c=await get('media',p).catch(()=>null);if(!c?.blob)await refreshMedia(p);n++}))}return n}
  window.BALI_mobileAdminCacheAllMedia=cacheAllMedia;
  const baseLoad=load;load=async function(){if(!navigator.onLine){if(loadSnapshot())return true;throw new Error('Нет интернета и локальной копии')}try{const out=await baseLoad();saveSnapshotNow();cacheAllMedia().catch(()=>{});return out}catch(e){if(loadSnapshot())return true;throw e}};
  const baseMark=mark;mark=function(){baseMark();scheduleSnapshot()};
  const baseEditC=editCocktail;editCocktail=function(){baseEditC();const c=cocktails.find(x=>x.id===current.id);if(c?.officialImage)hydrate('cpv',c.officialImage)};
  const baseEditI=editIngredient;editIngredient=function(){baseEditI();const i=ingredients.find(x=>x.id===current.id);if(i?.officialImage)hydrate('ipv',i.officialImage)};
  const baseImage=imageFile;imageFile=async function(file,obj,kind,preview){await baseImage(file,obj,kind,preview);const path=obj?.officialImage,b64=path?pending.get(path):null;if(path&&b64){await putDb('pending',{path,b64,savedAt:Date.now()}).catch(()=>{});await putDb('media',{path,blob:b64Blob(b64,mimeFor(path)),version:Number(manifest?.catalogVersion||0),savedAt:Date.now()}).catch(()=>{});scheduleSnapshot()}};
  const basePublish=publish;publish=async function(){if(!navigator.onLine){saveSnapshotNow();toast('Офлайн: изменения сохранены на устройстве. Подключите интернет и нажмите «Опубликовать».',true);return}const before=[...pending.keys()];await basePublish();if(!dirty&&!pending.size){for(const p of before)await delDb('pending',p).catch(()=>{});saveSnapshotNow();cacheAllMedia().catch(()=>{})}};$('publish').onclick=publish;
  const baseConnect=connect;connect=async function(){if(!navigator.onLine){token=$('token').value.trim()||localStorage.getItem('baliMobileAdminToken')||localStorage.getItem('baliAdminToken')||'';if(loadSnapshot()){await restorePending();$('login').classList.add('hidden');$('app').classList.remove('hidden');setWriteStatus(false,'Офлайн · редактирование доступно, публикация после подключения');toast('Открыта сохранённая локальная база');return}toast('Нет интернета и сохранённой базы. Один раз откройте ADMIN с интернетом.',true);return}return baseConnect()};$('connect').onclick=connect;
  if($('reload'))$('reload').onclick=async()=>{if(!navigator.onLine){loadSnapshot();toast('Офлайн · используется сохранённая база');return}if(dirty&&!confirm('Есть неопубликованные изменения. Загрузить данные с GitHub и потерять черновик?'))return;try{await load();toast('Данные обновлены и сохранены для офлайн-работы')}catch(e){toast('Не удалось обновить: '+e.message,true)}};
  window.addEventListener('online',()=>{setWriteStatus(true,'Интернет доступен · можно публиковать');if(!dirty)load().catch(()=>{});else cacheAllMedia().catch(()=>{})});
  window.addEventListener('offline',()=>{saveSnapshotNow();setWriteStatus(false,'Офлайн · локальная база доступна')});
  window.addEventListener('beforeunload',saveSnapshotNow);document.addEventListener('visibilitychange',()=>{if(document.hidden)saveSnapshotNow()});
  if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});restorePending().catch(()=>{});if(!navigator.onLine)loadSnapshot();
})();
