(() => {
  const D={selected:new Set(),search:'',category:'Все',org:'ООО «МАГИШТЫК»',director:'Н.И. Селех',startNo:''};
  const safe=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  function allCocktails(){try{return Array.isArray(globalThis.cocktails)?globalThis.cocktails:[]}catch(_){return[]}}
  function install(){if(document.getElementById('docPrintStyles'))return;const st=document.createElement('style');st.id='docPrintStyles';st.textContent=`
    .doc-print-layout{display:grid;grid-template-columns:360px 1fr;gap:16px}.doc-print-row{display:flex;gap:10px;align-items:center;padding:9px;border-bottom:1px solid var(--line)}.doc-print-row input{width:auto;margin:0}.doc-preview{background:#151519;border:1px solid var(--line);border-radius:16px;padding:16px;overflow:auto;min-height:650px}.official-card{width:210mm;height:297mm;box-sizing:border-box;background:#fff;color:#000;padding:18mm 20mm 16mm;font-family:'Times New Roman',Times,serif;font-size:10pt;line-height:1.12}.official-top{display:grid;grid-template-columns:1fr 1fr;gap:20mm;margin-bottom:10mm}.official-top .right{text-align:left}.official-small{font-size:8.5pt;font-style:italic}.official-approve{margin-top:5mm}.official-title{text-align:center;font-weight:700;font-size:12pt;margin:5mm 0 .5mm}.official-name{text-align:center;font-weight:700;font-style:italic;text-decoration:underline;margin-bottom:.5mm}.official-caption{text-align:center;font-size:8.5pt;margin-bottom:6mm}.official-section{font-weight:700;font-style:italic;margin:3mm 0 1mm}.official-table{width:100%;border-collapse:collapse;table-layout:fixed;font-size:9pt}.official-table th,.official-table td{border:.25mm solid #000;padding:1.1mm 1.5mm;vertical-align:middle}.official-table th{text-align:center;font-style:italic;font-weight:700}.official-table td:first-child{font-style:italic}.official-table .center{text-align:center}.official-output td{font-weight:700;font-style:italic}.official-nutrition th{font-size:8.3pt}.official-card-page{page-break-after:always;break-after:page}.official-card-page:last-child{page-break-after:auto;break-after:auto}#docPrintRoot{display:none}
    @media(max-width:1000px){.doc-print-layout{grid-template-columns:1fr}}
    @media print{@page{size:A4 portrait;margin:0}body>*:not(#docPrintRoot){display:none!important}#docPrintRoot{display:block!important}.official-card{margin:0!important}}
  `;document.head.appendChild(st)}
  function ensure(){install();const nav=document.querySelector('.nav'),main=document.querySelector('#app main');if(!nav||!main)return false;const bar=document.getElementById('printNavButton');if(bar)bar.textContent='Печать техкарт для бармена';
    if(!document.getElementById('docPrintNav')){const b=document.createElement('button');b.id='docPrintNav';b.textContent='Печать техкарт для документов';b.onclick=open;nav.appendChild(b)}
    if(!document.getElementById('docprint')){const s=document.createElement('section');s.id='docprint';s.className='view hidden';s.innerHTML=`<div class="top"><div><div class="title">Печать техкарт для документов</div><div class="muted">Официальный шаблон A4 по загруженному образцу. Одна техкарта — один лист A4.</div></div><div class="actions"><button id="docPrintBtn" class="primary">Печать / PDF</button></div></div><div class="doc-print-layout"><div class="card"><label>Организация-разработчик</label><input id="docOrg" value="${safe(D.org)}"><label>Директор / утверждающее лицо</label><input id="docDirector" value="${safe(D.director)}"><label>№ первой техкарты (необязательно)</label><input id="docNumber" value=""><label>Поиск</label><input id="docSearch" class="search" placeholder="Название коктейля"><label>Категория</label><select id="docCategory"><option>Все</option><option>Авторские</option><option>Классика</option><option>Заготовки</option></select><div class="actions" style="margin:10px 0"><button id="docVisible" class="ghost">Выбрать видимые</button><button id="docClear" class="ghost">Снять</button></div><div id="docCount" class="muted"></div><div id="docList" style="max-height:480px;overflow:auto"></div></div><div class="card"><div class="section-title" style="margin-top:0">Предпросмотр документа A4</div><div id="docPreview" class="doc-preview"></div><div class="muted" style="margin-top:8px">Показатели пищевой/энергетической ценности остаются пустыми, если они не заданы в данных — система их не выдумывает.</div></div></div>`;main.appendChild(s);document.body.insertAdjacentHTML('beforeend','<div id="docPrintRoot"></div>');bind()}return true}
  function open(){if(!ensure())return;document.querySelectorAll('.view').forEach(v=>v.classList.add('hidden'));document.getElementById('docprint').classList.remove('hidden');document.querySelectorAll('.nav button').forEach(b=>b.classList.remove('active'));document.getElementById('docPrintNav').classList.add('active');render()}
  function visible(){const q=D.search.trim().toLowerCase();return allCocktails().filter(c=>(D.category==='Все'||c.category===D.category)&&(!q||(c.name||'').toLowerCase().includes(q))).sort((a,b)=>(a.name||'').localeCompare(b.name||'','ru'))}
  function bind(){document.getElementById('docOrg').oninput=e=>{D.org=e.target.value;preview()};document.getElementById('docDirector').oninput=e=>{D.director=e.target.value;preview()};document.getElementById('docNumber').oninput=e=>{D.startNo=e.target.value;preview()};document.getElementById('docSearch').oninput=e=>{D.search=e.target.value;render()};document.getElementById('docCategory').onchange=e=>{D.category=e.target.value;render()};document.getElementById('docVisible').onclick=()=>{visible().forEach(c=>D.selected.add(c.id));render()};document.getElementById('docClear').onclick=()=>{D.selected.clear();render()};document.getElementById('docPrintBtn').onclick=()=>{const arr=allCocktails().filter(c=>D.selected.has(c.id));if(!arr.length)return alert('Выберите техкарты');document.getElementById('docPrintRoot').innerHTML=arr.map((c,i)=>markup(c,i)).join('');setTimeout(()=>window.print(),80)}}
  function render(){const el=document.getElementById('docList'),arr=visible();el.innerHTML=arr.map(c=>`<label class="doc-print-row"><input type="checkbox" data-id="${safe(c.id)}" ${D.selected.has(c.id)?'checked':''}><span><b>${safe(c.name)}</b><br><small class="muted">${safe(c.category)}</small></span></label>`).join('')||'<div class="empty">Ничего не найдено</div>';el.querySelectorAll('input').forEach(x=>x.onchange=()=>{x.checked?D.selected.add(x.dataset.id):D.selected.delete(x.dataset.id);count();preview()});count();preview()}
  function count(){const e=document.getElementById('docCount');if(e)e.textContent='Выбрано: '+D.selected.size}
  function amountText(i){return safe(i?.amount??'')}
  function numberFor(idx){if(D.startNo===''||D.startNo==null)return '';const n=Number(D.startNo);return Number.isFinite(n)?String(n+idx):safe(D.startNo)}
  function markup(c,idx){const ins=c.ingredients||[];let rows=ins.map(i=>`<tr><td>${safe(i.name)}</td><td class="center">${amountText(i)}</td><td class="center">${amountText(i)}</td></tr>`).join('');for(let k=ins.length;k<Math.max(10,ins.length);k++)rows+='<tr><td>&nbsp;</td><td></td><td></td></tr>';const output=safe(c.yield||c.yieldText||'');return `<div class="official-card official-card-page"><div class="official-top"><div><div class="official-small">Наименование организации разработчика</div><div style="margin-top:4mm"><b>${safe(D.org)}</b></div><div style="margin-top:8mm" class="official-small">Директор</div></div><div class="right"><div class="official-small" style="margin-top:8mm">Утверждаю</div><div class="official-approve">От «___» __________ 20__ г. &nbsp; <b>${safe(D.director)}</b></div></div></div><div class="official-title">Технологическая карта &nbsp;&nbsp; № ${numberFor(idx)}</div><div class="official-name">« ${safe(c.name)} »</div><div class="official-caption">наименование барной продукции</div><div class="official-section">1. Рецептура</div><table class="official-table"><colgroup><col style="width:52%"><col style="width:24%"><col style="width:24%"></colgroup><thead><tr><th rowspan="2">НАИМЕНОВАНИЕ СЫРЬЯ</th><th colspan="2">Расход сырья на 1 п готовой продукции</th></tr><tr><th>БРУТТО</th><th>НЕТТО</th></tr></thead><tbody>${rows}<tr class="official-output"><td>ВЫХОД ГОТОВОЙ ПРОДУКЦИИ</td><td></td><td class="center">${output}</td></tr></tbody></table><div class="official-section" style="margin-top:8mm">2. Сведения о пищевой и энергетической ценности.</div><table class="official-table official-nutrition"><thead><tr><th>БЕЛКИ, ГР</th><th>ЖИРЫ, ГР</th><th>УГЛЕВОДЫ, ГР</th><th>ЭНЕРГЕТИЧЕСКАЯ ЦЕННОСТЬ</th></tr></thead><tbody><tr style="height:12mm"><td></td><td></td><td></td><td></td></tr></tbody></table></div>`}
  function preview(){const c=allCocktails().find(x=>D.selected.has(x.id));const p=document.getElementById('docPreview');if(!p)return;p.innerHTML=c?`<div style="transform:scale(.57);transform-origin:top center;height:650px">${markup(c,0)}</div>`:'<div class="empty">Выберите техкарту для предпросмотра</div>'}
  install();setTimeout(ensure,0);new MutationObserver(()=>ensure()).observe(document.body,{childList:true,subtree:true});window.openDocumentTechPrint=open;
})();