(() => {
  const state={selected:new Set(),search:'',category:'Все',mode:'bartender',size:150,showIngredientPhotos:true};
  const safe=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  const getC=()=>{try{return Array.isArray(cocktails)?cocktails:[]}catch(_){return[]}};
  const getI=()=>{try{return Array.isArray(ingredients)?ingredients:[]}catch(_){return[]}};
  const img=p=>{if(!p)return'';try{return rawUrl(p)}catch(_){return`https://raw.githubusercontent.com/Nik13599/BALI-COCKTAIL-v1/main/${p}`}};
  const ref=i=>getI().find(x=>x.id===i.ingredientId)||getI().find(x=>String(x.name).toLowerCase()===String(i.name).toLowerCase())||null;
  function kg(item){const a=Number(item?.amount);if(!Number.isFinite(a))return'';const u=String(item?.unit||'').toLowerCase();if(u.includes('мл')||u.includes('г'))return(a/1000).toFixed(3);if(u.includes('кг'))return a.toFixed(3);return''}
  function yieldKg(c){const m=String(c?.yield||'').match(/([0-9]+(?:[.,][0-9]+)?)/);if(!m)return'';const n=Number(m[1].replace(',','.'));return Number.isFinite(n)?(n/1000).toFixed(3):''}

  function styles(){
    if(document.getElementById('baliPrintStyles'))return;const s=document.createElement('style');s.id='baliPrintStyles';s.textContent=`
    .print-layout{display:grid;grid-template-columns:390px 1fr;gap:16px}.print-controls{display:grid;grid-template-columns:1fr 1fr;gap:10px}.print-mode{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-bottom:10px}.print-mode button{border:1px solid var(--line);background:var(--panel2);color:#fff;border-radius:12px;padding:11px;font-weight:800;cursor:pointer}.print-mode button.active{background:var(--accent);border-color:var(--accent)}
    .print-check{display:flex;align-items:center;gap:10px;padding:9px 10px;border:1px solid transparent;border-radius:12px;cursor:pointer}.print-check:hover{background:var(--panel2);border-color:var(--line)}.print-check input{width:auto;margin:0}.print-check small{display:block;color:var(--muted)}
    .print-preview-shell{display:flex;justify-content:center;align-items:flex-start;min-height:620px;padding:18px;background:#101014;border-radius:18px;border:1px solid var(--line);overflow:auto}
    .tech-print-card{position:relative;background:#fff;color:#111;box-sizing:border-box;overflow:hidden;font-family:Arial,Helvetica,sans-serif;display:flex;flex-direction:column}.tech-print-card *{box-sizing:border-box}.tech-print-inner{padding:6mm;display:flex;flex-direction:column;height:100%;gap:2.4mm}.tech-print-head{display:flex;justify-content:space-between;gap:5mm;align-items:flex-start;border-bottom:.35mm solid #111;padding-bottom:2.3mm}.tech-print-brand{font-weight:900;font-size:8.5pt;letter-spacing:1.4pt}.tech-print-category{font-size:7pt;text-transform:uppercase;letter-spacing:.8pt;color:#6b1830;margin-top:1mm;font-weight:700}.tech-print-title{font-size:18pt;font-weight:900;line-height:1.02;max-width:70%;text-align:right}
    .tech-print-top{display:grid;grid-template-columns:38% 1fr;gap:4mm;min-height:34mm}.tech-print-photo{width:100%;height:34mm;object-fit:cover;border:.25mm solid #bbb;background:#eee}.tech-print-no-photo{height:34mm;border:.25mm solid #bbb;background:#f1f1f1;display:grid;place-items:center;text-align:center;font-size:7pt;color:#777;padding:3mm}.tech-print-specs{display:grid;grid-template-columns:1fr 1fr;gap:2mm}.tech-print-spec{border:.25mm solid #bbb;padding:2mm}.tech-print-spec span{display:block;font-size:6.5pt;text-transform:uppercase;color:#666;font-weight:700}.tech-print-spec b{display:block;font-size:8.5pt;margin-top:.8mm}.tech-print-taste{font-size:7.5pt;line-height:1.25;color:#333}.tech-print-section{font-size:8.2pt;font-weight:900;text-transform:uppercase;letter-spacing:.7pt;border-bottom:.25mm solid #bbb;padding-bottom:1mm}.tech-print-ings{display:grid;grid-template-columns:1fr 1fr;gap:1.2mm 4mm}.tech-print-ing{display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:1.5mm;font-size:7.2pt;min-width:0}.tech-print-ing img{width:9mm;height:9mm;object-fit:contain;border:.2mm solid #ccc;border-radius:1.4mm;background:#fff}.tech-print-ing-name{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.tech-print-ing-amount{font-weight:700;white-space:nowrap}.tech-print-steps{display:grid;grid-template-columns:1fr 1fr;gap:1.1mm 4mm;font-size:6.8pt;line-height:1.22}.tech-print-step{display:flex;gap:1.4mm}.tech-print-step-num{flex:0 0 5mm;height:5mm;border-radius:50%;background:#6b1830;color:#fff;display:grid;place-items:center;font-size:6.2pt;font-weight:800}.tech-print-footer{margin-top:auto;display:flex;justify-content:space-between;border-top:.25mm solid #bbb;padding-top:1.4mm;color:#777;font-size:6.2pt}
    .doc-tech{width:210mm;min-height:297mm;background:white;color:#111;padding:13mm 14mm 12mm;font-family:"Times New Roman",serif;box-sizing:border-box}.doc-tech *{box-sizing:border-box}.doc-title{text-align:center;font-weight:700;font-size:15pt;letter-spacing:.4px;margin-bottom:8mm}.doc-line{display:grid;grid-template-columns:48mm 1fr;border-bottom:1px solid #111;min-height:8mm;align-items:end;margin:2mm 0}.doc-line .l{font-size:9pt;padding-bottom:1.5mm}.doc-line .v{text-align:center;font-weight:700;padding-bottom:1.5mm}.doc-table{width:100%;border-collapse:collapse;margin-top:5mm;font-size:8pt}.doc-table th,.doc-table td{border:1px solid #111;padding:2.2mm 1.4mm;text-align:center;vertical-align:middle}.doc-table th{font-weight:700}.doc-table td:first-child{text-align:left}.doc-out{margin-top:5mm;display:flex;gap:8mm;font-size:9pt}.doc-out b{min-width:35mm;border-bottom:1px solid #111;text-align:center}.doc-block{margin-top:6mm}.doc-block h3{font-size:10pt;margin:0 0 2mm;text-transform:uppercase}.doc-block div{border:1px solid #111;min-height:20mm;padding:3mm;font-size:9pt;line-height:1.35}.doc-sign{margin-top:9mm;display:grid;grid-template-columns:45mm 1fr 45mm;gap:4mm;font-size:9pt;align-items:end}.doc-sign span{border-bottom:1px solid #111;min-height:7mm}
    #printRoot{display:none}@media(max-width:1000px){.print-layout{grid-template-columns:1fr}.print-preview-shell{min-height:420px}}@media print{body{background:#fff!important}body>*:not(#printRoot){display:none!important}#printRoot{display:block!important;margin:0!important;padding:0!important}#printRoot>*{page-break-after:always;break-after:page;margin:0!important;box-shadow:none!important}#printRoot>*:last-child{page-break-after:auto;break-after:auto}@page{margin:0}}
    `;document.head.appendChild(s)
  }
  function ensure(){
    styles();const nav=document.querySelector('.nav'),main=document.querySelector('#app main');if(!nav||!main)return false;
    if(!document.getElementById('printNavButton')){const b=document.createElement('button');b.id='printNavButton';b.textContent='Печать техкарт';b.onclick=open;nav.appendChild(b)}
    if(!document.getElementById('printcards')){const sec=document.createElement('section');sec.id='printcards';sec.className='view hidden';sec.innerHTML=`
      <div class="top"><div><div class="title">Печать техкарт</div><div class="muted">Два режима: рабочие карточки для бармена и A4 для документации</div></div><div class="actions"><button id="printSelectedCards" class="primary">Печать / PDF</button></div></div>
      <div class="print-layout"><div class="card"><div class="print-mode"><button id="modeBartender" class="active">Для бармена</button><button id="modeDocs">Для документов</button></div>
      <div id="bartenderOpts"><div class="print-controls"><div><label>Размер карточки</label><select id="printSize"><option value="120">120 × 120 мм</option><option value="150" selected>150 × 150 мм</option><option value="180">180 × 180 мм</option><option value="200">200 × 200 мм</option></select></div><div><label>Категория</label><select id="printCategory"><option>Все</option><option>Авторские</option><option>Классика</option><option>Заготовки</option></select></div></div><label style="display:flex;align-items:center;gap:8px"><input id="printIngredientPhotos" type="checkbox" checked style="width:auto">Показывать фотографии ингредиентов</label></div>
      <div id="docsOpts" class="hidden"><div class="muted" style="padding:8px 0">Формат A4. Шаблон повторяет бумажную технологическую карту: сырьё, брутто/нетто, отходы, потери, выход, органолептика и технология приготовления.</div></div>
      <label>Поиск</label><input id="printSearch" class="search" placeholder="Название коктейля"><div class="actions" style="margin:10px 0"><button id="printSelectVisible" class="ghost">Выбрать видимые</button><button id="printClear" class="ghost">Снять выбор</button></div><div id="printCount" class="muted" style="margin-bottom:8px"></div><div id="printCocktailList" style="max-height:470px;overflow:auto"></div></div>
      <div class="card"><div class="section-title" style="margin-top:0">Предпросмотр</div><div id="printPreview" class="print-preview-shell"><div class="empty">Выберите хотя бы одну техкарту</div></div></div></div>`;main.appendChild(sec);document.body.insertAdjacentHTML('beforeend','<div id="printRoot"></div>');bind()}
    return true
  }
  function open(){if(!ensure())return;document.querySelectorAll('.view').forEach(v=>v.classList.add('hidden'));document.getElementById('printcards').classList.remove('hidden');document.querySelectorAll('.nav button').forEach(b=>b.classList.remove('active'));document.getElementById('printNavButton').classList.add('active');renderList()}
  function visible(){const q=state.search.toLowerCase().trim();return getC().filter(c=>(state.category==='Все'||c.category===state.category)&&(!q||String(c.name).toLowerCase().includes(q))).sort((a,b)=>String(a.name).localeCompare(String(b.name),'ru'))}
  function bind(){
    document.getElementById('modeBartender').onclick=()=>setMode('bartender');document.getElementById('modeDocs').onclick=()=>setMode('docs');
    document.getElementById('printSize').onchange=e=>{state.size=Number(e.target.value);preview()};document.getElementById('printCategory').onchange=e=>{state.category=e.target.value;renderList()};document.getElementById('printSearch').oninput=e=>{state.search=e.target.value;renderList()};document.getElementById('printIngredientPhotos').onchange=e=>{state.showIngredientPhotos=e.target.checked;preview()};
    document.getElementById('printSelectVisible').onclick=()=>{visible().forEach(c=>state.selected.add(c.id));renderList()};document.getElementById('printClear').onclick=()=>{state.selected.clear();renderList()};document.getElementById('printSelectedCards').onclick=print
  }
  function setMode(m){state.mode=m;document.getElementById('modeBartender').classList.toggle('active',m==='bartender');document.getElementById('modeDocs').classList.toggle('active',m==='docs');document.getElementById('bartenderOpts').classList.toggle('hidden',m!=='bartender');document.getElementById('docsOpts').classList.toggle('hidden',m!=='docs');preview()}
  function renderList(){if(!ensure())return;const el=document.getElementById('printCocktailList'),arr=visible();el.innerHTML=arr.map(c=>`<label class="print-check"><input type="checkbox" data-id="${safe(c.id)}" ${state.selected.has(c.id)?'checked':''}><span><b>${safe(c.name)}</b><small>${safe(c.category)} · ${safe(c.method||'')}</small></span></label>`).join('')||'<div class="empty">Ничего не найдено</div>';el.querySelectorAll('input').forEach(x=>x.onchange=()=>{x.checked?state.selected.add(x.dataset.id):state.selected.delete(x.dataset.id);count();preview()});count();preview()}
  function count(){const e=document.getElementById('printCount');if(e)e.textContent=`Выбрано: ${state.selected.size}`}
  function ingMarkup(i){const r=ref(i),im=state.showIngredientPhotos&&r?.officialImage?`<img src="${safe(img(r.officialImage))}" alt="">`:'';return`<div class="tech-print-ing">${im}<span class="tech-print-ing-name">${safe(i.name)}</span><span class="tech-print-ing-amount">${safe(i.amount)} ${safe(i.unit)}</span></div>`}
  function bartender(c,size){const photo=c.officialImage?`<img class="tech-print-photo" src="${safe(img(c.officialImage))}">`:'<div class="tech-print-no-photo">Эталонное фото<br>не загружено</div>';return`<article class="tech-print-card" style="width:${size}mm;height:${size}mm"><div class="tech-print-inner"><div class="tech-print-head"><div><div class="tech-print-brand">BALI COCKTAIL</div><div class="tech-print-category">${safe(c.category)}</div></div><div class="tech-print-title">${safe(c.name)}</div></div><div class="tech-print-top">${photo}<div><div class="tech-print-specs"><div class="tech-print-spec"><span>Выход</span><b>${safe(c.yield)}</b></div><div class="tech-print-spec"><span>Метод</span><b>${safe(c.method)}</b></div><div class="tech-print-spec"><span>Бокал</span><b>${safe(c.glass)}</b></div><div class="tech-print-spec"><span>Лёд</span><b>${safe(c.ice)}</b></div></div><div class="tech-print-taste" style="margin-top:2mm">${safe(c.taste||'')}</div></div></div><div class="tech-print-section">Ингредиенты</div><div class="tech-print-ings">${(c.ingredients||[]).map(ingMarkup).join('')}</div><div class="tech-print-section">Приготовление</div><div class="tech-print-steps">${(c.steps||[]).map((s,i)=>`<div class="tech-print-step"><span class="tech-print-step-num">${i+1}</span><span>${safe(s)}</span></div>`).join('')}</div><div class="tech-print-footer"><span>Технологическая карта BALI</span><span>Каталог v${safe((typeof manifest!=='undefined'&&manifest?.catalogVersion)||'')}</span></div></div></article>`}
  function docs(c){const rows=(c.ingredients||[]).map(i=>{const k=kg(i);return`<tr><td>${safe(i.name)}</td><td>${k}</td><td>0</td><td>${k}</td><td>0</td><td>${k}</td></tr>`}).join('');return`<article class="doc-tech"><div class="doc-title">ТЕХНОЛОГИЧЕСКАЯ КАРТА</div><div class="doc-line"><div class="l">Наименование блюда (изделия)</div><div class="v">${safe(c.name)}</div></div><div class="doc-line"><div class="l">Вид обработки</div><div class="v">${safe(c.method||'')}</div></div><table class="doc-table"><thead><tr><th>Наименование сырья</th><th>Вес брутто (кг)</th><th>Норма отходов %</th><th>Вес нетто (кг)</th><th>Потери при технологической обработке %</th><th>Вес готовой продукции (кг)</th></tr></thead><tbody>${rows}</tbody></table><div class="doc-out">Выход готовой продукции (кг): <b>${yieldKg(c)}</b></div><div class="doc-block"><h3>Органолептические показатели</h3><div>${safe(c.taste||'')}</div></div><div class="doc-block"><h3>Технология приготовления</h3><div>${(c.steps||[]).map((s,i)=>`${i+1}. ${safe(s)}`).join('<br>')}</div></div><div class="doc-sign"><div>Составил:</div><span></span><div>Дата: ____________</div></div></article>`}
  function preview(){const p=document.getElementById('printPreview');if(!p)return;const c=getC().find(x=>state.selected.has(x.id));if(!c){p.innerHTML='<div class="empty">Выберите хотя бы одну техкарту</div>';return}if(state.mode==='docs'){p.innerHTML=`<div style="transform:scale(.55);transform-origin:top center;height:635px">${docs(c)}</div>`}else{const sc=Math.min(1,520/(state.size*3.7795));p.innerHTML=`<div style="transform:scale(${sc});transform-origin:top center;height:${state.size*3.7795*sc}px">${bartender(c,state.size)}</div>`}}
  function print(){const arr=getC().filter(c=>state.selected.has(c.id));if(!arr.length)return toast('Выберите техкарты для печати',true);const root=document.getElementById('printRoot');root.innerHTML=state.mode==='docs'?arr.map(docs).join(''):arr.map(c=>bartender(c,state.size)).join('');const st=document.getElementById('dynamicPrintPage')||document.head.appendChild(Object.assign(document.createElement('style'),{id:'dynamicPrintPage'}));st.textContent=state.mode==='docs'?'@page{size:A4 portrait;margin:0}':`@page{size:${state.size}mm ${state.size}mm;margin:0}`;setTimeout(()=>window.print(),120)}
  const obs=new MutationObserver(()=>ensure());obs.observe(document.documentElement,{childList:true,subtree:true});ensure()
})();