(() => {
const CATEGORY_ORDER=['Виски','Ром','Джин','Текила','Водка','Ликёры','Вермуты','Коньяк / бренди','Пиво','Белое вино','Красное вино','Шампанское / игристое вино','Безалкогольное вино','Напитки','Кофе / чай'];
const SOURCE_ROWS={
'Виски':[
['Laphroaig Selekt','Scotland','40 мл',60,'700 мл',1500],['Macallan 12','Scotland','40 мл',90,'700 мл',1575],['Macallan 15','Scotland','40 мл',null,'700 мл',2500],['Macallan 18','Scotland','40 мл',null,'700 мл',5000],['Glenfiddich 12','Scotland','40 мл',34,'700 мл',595],['Glenfiddich 15','Scotland','40 мл',86,'700 мл',1505],['Johnnie Walker RED Label','Scotland','40 мл',22,'1000 мл',550],['Johnnie Walker BLACK Label','Scotland','40 мл',36,'1000 мл',900],['Johnnie Walker BLUE Label','Scotland','40 мл',null,'700 мл',3000],['Tullamore D.E.W.','Ireland','40 мл',30,'700 мл',525],["Jack Daniel's",'USA','40 мл',30,'700 мл',750],["Jack Daniel's Fire",'USA','40 мл',38,'700 мл',665],['The Deacon','Scotland','40 мл',34,'700 мл',595],['Monkey Shoulder','Scotland','40 мл',34,'700 мл',850],["Maker's Mark",'USA','40 мл',36,'1000 мл',900],["Jack Daniel's Honey",'USA','40 мл',32,'700 мл',560],['Bushmills','Ireland','40 мл',18,'1000 мл',450],['Chivas Regal 12','Scotland','40 мл',32,'1000 мл',800],['Chivas Regal 18','Scotland','40 мл',null,'700 мл',1500],['Chivas Regal 21','Scotland','40 мл',null,'700 мл',2200],['Jameson','Ireland','40 мл',23,'1000 мл',575],['Jameson Crested','Ireland','40 мл',32,'700 мл',560],['Jameson Stout Edition','Ireland','40 мл',28,'700 мл',490]],
'Ром':[['Bumbu The Original','Barbados','40 мл',32,'700 мл',560],['Bumbu XO','Barbados','40 мл',40,'700 мл',700],['Matusalem Gran Reserva 15','Dominican','40 мл',34,'700 мл',595],['Matusalem Gran Reserva 23','Dominican','40 мл',null,'700 мл',1300],['Plantation Original Dark','France','40 мл',24,'700 мл',420],['Plantation Pineapple','France','40 мл',34,'700 мл',595],['Plantation XO','France','40 мл',44,'700 мл',770],['Dictador 12','Columbia','40 мл',34,'700 мл',595],['Bacardi Negra','Cuba','40 мл',20,'1000 мл',500],['Bacardi Spiced','Cuba','40 мл',22,'1000 мл',550],['Captain Morgan Dark','Jamaica','40 мл',20,'1000 мл',500],['Captain Morgan Spiced','Jamaica','40 мл',22,'1000 мл',550],['Kraken','London','40 мл',26,'1000 мл',650]],
'Джин':[['Bulldog','London','40 мл',34,'700 мл',595],['Bombay','London','40 мл',24,'1000 мл',600],["Hendrick's",'Scotland','40 мл',38,'700 мл',665],['Monkey 47','Germany','40 мл',32,'500 мл',400],['Beefeater','London','40 мл',22,'500 мл',275]],
'Текила':[['Espolon Blanco','Mexico','40 мл',24,'750 мл',450],['Espolon Reposado','Mexico','40 мл',24,'750 мл',450],['Patron Reposado','Mexico','40 мл',60,'700 мл',1050],['Patron Silver','Mexico','40 мл',60,'700 мл',1050],['Clase Azul Reposado','Mexico','40 мл',null,'700 мл',3000]],
'Водка':[['Grey Goose','France','40 мл',38,'1000 мл',950],['Finlandia','Finland','40 мл',20,'1000 мл',500],['Absolut','Sweden','40 мл',20,'700 мл',350],['Vseslav Charodey','Belarus','40 мл',18,'700 мл',315]],
'Ликёры':[['Campari','Italy','40 мл',20,'1000 мл',500],['Cynar','Italy','40 мл',24,'700 мл',420],['Frangelico','Italy','40 мл',30,'700 мл',525],['Aperol','Italy','40 мл',20,'1000 мл',500],['Sarti Rosa','Italy','40 мл',22,'700 мл',385],['Bumbu Cream','Barbados','40 мл',26,'700 мл',455],['Jagermeister','Germany','40 мл',22,'1000 мл',550],['Jagermeister Manifest','Germany','40 мл',32,'1000 мл',800],['Jagermeister Orange','Germany','40 мл',30,'1000 мл',750],['Becherovka','Czech Republic','40 мл',20,'700 мл',350],['Fireball','Canada','40 мл',20,'1000 мл',500],['Absent Pernod','France','40 мл',30,'700 мл',525]],
'Вермуты':[['Martini Extra Dry','Italy','40 мл',14,'1000 мл',350],['Martini Rosso','Italy','40 мл',14,'1000 мл',350],['Martini Bianco','Italy','40 мл',14,'1000 мл',350],['Martini Fiero','Italy','40 мл',16,'1000 мл',400]],
'Коньяк / бренди':[['Courvoisier VS','France','40 мл',60,'700 мл',1050],['Courvoisier VSOP','France','40 мл',64,'700 мл',1120],['Hennessy VS','France','40 мл',44,'700 мл',770],['Hennessy VSOP','France','40 мл',70,'700 мл',1225],['Hennessy XO','France','40 мл',240,'700 мл',4200],['Torres 10','Spain','40 мл',22,'700 мл',385]],
'Пиво':[['Miller','Belarus','450 мл',15,'',null],['Maison Arne Blanche','Belarus','400 мл',15,'',null],['Krushovice Alco 0%','Belarus','330 мл',10,'',null],['Corona Extra','Mexico','335 мл',20,'',null]],
'Белое вино':[['Casillero De Diablo Sauv. Blanc сухое','Chile','125 мл',24,'Бутылка',144],['Villa Wolf Gewurztraminer полусухое','Germany','125 мл',36,'Бутылка',216],['1D Chablis Premier Cru сухое','France','125 мл',200,'Бутылка',1200],['Gustave Lorenz Riesling reserv полусухое','France','125 мл',38,'Бутылка',228],['Domaine Marguerite Carillon сухое','France','125 мл',30,'Бутылка',180]],
'Красное вино':[['Casillero De Diablo Carmenere сухое','Chile','125 мл',24,'Бутылка',144],['Planeta La Segreta Il Rosso сухое','Italy','125 мл',36,'Бутылка',216],["Ca'Bianca Barolo DOCG сухое",'Italy','125 мл',150,'Бутылка',900],['Cioccolate Tube Primitivo полусухое','Italy','125 мл',40,'Бутылка',240],['The Dogfather Zinfandel Reserve полусухое','USA','125 мл',46,'Бутылка',276]],
'Шампанское / игристое вино':[['Cin Zano Asti','Italy','125 мл',28,'Бутылка',168],['Prosecco Bea Vita','Italy','125 мл',26,'Бутылка',156],['Mazet Brut','France','125 мл',26,'Бутылка',156],['Luc Belaire розовое сухое','France','',null,'Бутылка',500],['Luc Belaire белое брют','France','',null,'Бутылка',500],['Veuve Clicquot Brut белое брют','France','',null,'Бутылка',1500],['Moet & Chandon Brut белое брют','France','',null,'Бутылка',850],['Moet & Chandon Brut розовое брют','France','',null,'Бутылка',950],['Bottega Gold Prosecco белое брют','Italy','125 мл',75,'Бутылка',450],['Bottega Rose Gold Pinot Nero розовое брют','Italy','125 мл',90,'Бутылка',540],['Mumm белое брют','France','',null,'Бутылка',750],['Dom Perignon Brut','France','',null,'Бутылка',6000],['Ruinart, Blanc de Blancs','France','',null,'Бутылка',3000]],
'Безалкогольное вино':[['Nozeco игристое','France','125 мл',18,'Бутылка',108],['Light house белое','Germany','125 мл',18,'Бутылка',108],['Light house розовое','Germany','125 мл',18,'Бутылка',108]],
'Напитки':[['Рич апельсин/вишня/яблоко/томат','Belarus','200 мл',10,'',null],['Кока-кола/Швепс/Спрайт','Belarus','330 мл',10,'',null],['Кока-кола зеро','Belarus','330 мл',10,'',null],['Red Bull','Austria','250 мл',15,'',null],['Red Bull зеро','Austria','250 мл',15,'',null],['Боровая газ/негаз','Belarus','200 мл',10,'',null],['Tassay газ/негаз','Kazakhstan','750 мл',40,'',null]],
'Кофе / чай':[['Американо','','',10,'',null],['Эспрессо','','',10,'',null],['Черный чай','','',10,'',null],['Зеленый чай','','',10,'',null]]
};
function defaultProducts(){let out=[];for(const cat of CATEGORY_ORDER){(SOURCE_ROWS[cat]||[]).forEach((r,idx)=>out.push({id:`product-${cat}-${idx}`.replace(/[^a-zа-я0-9-]+/gi,'-').toLowerCase(),category:cat,name:r[0],country:r[1]||'',portionLabel:r[2]||'',portionPrice:r[3]??null,bottleVolume:r[4]||'',bottlePrice:r[5]??null,active:true,order:idx+1,comment:''}))}return out}
const state={selected:new Set(),search:'',category:'Все',current:null};
const money=v=>v===null||v===''?'—':`${new Intl.NumberFormat('ru-RU',{maximumFractionDigits:2}).format(Number(v))} BYN`;
function ensureProducts(){registerNavButton('products','Продукция');if(!document.getElementById('products')){const s=document.createElement('section');s.id='products';s.className='view hidden';s.innerHTML=`<div class="top"><div><div class="title">Продукция</div><div class="muted">Алкогольная и безалкогольная продукция · цены в белорусских рублях</div></div><div class="actions"><button id="productAdd" class="ghost">+ Добавить позицию</button><button id="productPrint" class="ghost">Печать выбранного A4 / PDF</button><button class="primary publish">Опубликовать</button></div></div><div class="product-grid"><div class="card"><div class="product-toolbar"><input id="productSearch" class="search" placeholder="Поиск продукции"><select id="productCategory"><option>Все</option></select></div><div class="actions" style="margin:0 0 10px"><button id="productSelectVisible" class="ghost">Выбрать видимые</button><button id="productClearSelection" class="ghost">Снять выбор</button></div><div id="productSelectedCount" class="muted" style="margin-bottom:8px"></div><div id="productList" class="product-list"></div></div><div id="productEditor" class="card"><div class="empty">Выберите позицию слева</div></div></div>`;document.querySelector('#app main').appendChild(s);document.body.insertAdjacentHTML('beforeend','<div id="productPrintRoot"></div>');installProductStyles();bindProductControls()}if(!barProducts.length){barProducts=defaultProducts();window.barMenuDirty=true;markDirty();toast('Стартовый перечень продукции загружен. Проверьте цены и опубликуйте.')}$('kProducts')&&($('kProducts').textContent=barProducts.length);renderProducts()}
function installProductStyles(){if(document.getElementById('productStyles'))return;const s=document.createElement('style');s.id='productStyles';s.textContent=`.product-grid{display:grid;grid-template-columns:minmax(560px,650px) minmax(420px,1fr);gap:16px}.product-toolbar{display:grid;grid-template-columns:minmax(300px,1fr) 250px;gap:10px}.product-list{max-height:calc(100vh - 240px);overflow:auto}.product-row{display:grid;grid-template-columns:26px minmax(220px,1fr) 145px 150px;gap:10px;align-items:center;padding:10px;border:1px solid transparent;border-radius:12px;cursor:pointer}.product-row:hover,.product-row.active{background:var(--panel2);border-color:var(--line)}.product-row.off{opacity:.45}.product-row input[type=checkbox]{width:auto;margin:0}.product-main b{display:block;white-space:normal}.product-main small,.product-money small{display:block;color:var(--muted)}.product-money{font-size:12px;text-align:right}.product-money b{font-size:13px;color:#fff;white-space:nowrap}.a4-products{font-family:Arial,sans-serif;color:#111;background:#fff}.a4-products h1{text-align:center;font-size:16pt;margin:0 0 5mm}.a4-products .date{text-align:right;font-size:8pt;margin-bottom:4mm}.a4-category{break-inside:auto;margin:0 0 5mm}.a4-category h2{font-size:13pt;margin:3mm 0 1.8mm;border-bottom:.45mm solid #111;padding-bottom:1mm;break-after:avoid}.a4-table{width:100%;border-collapse:collapse;font-size:8.8pt}.a4-table th,.a4-table td{border:.2mm solid #555;padding:1.4mm 1.7mm;vertical-align:top}.a4-table th{background:#eee;text-align:left}.a4-table td.num{text-align:right;white-space:nowrap}.a4-note{font-size:7.5pt;margin-top:5mm;color:#555}@media(max-width:1200px){.product-grid{grid-template-columns:1fr}.product-list{max-height:430px}}@media print{body>*:not(#productPrintRoot){display:none!important}#productPrintRoot{display:block!important;background:#fff!important}@page{size:A4 portrait;margin:12mm}.a4-products{display:block!important}.a4-table tr{break-inside:avoid}}`;document.head.appendChild(s)}
function productCategories(){return [...new Set([...CATEGORY_ORDER,...barProducts.map(x=>x.category).filter(Boolean)])]}
function visibleProducts(){const q=state.search.trim().toLowerCase();return barProducts.filter(p=>(state.category==='Все'||p.category===state.category)&&(!q||`${p.name} ${p.country}`.toLowerCase().includes(q))).sort((a,b)=>productCategories().indexOf(a.category)-productCategories().indexOf(b.category)||Number(a.order||0)-Number(b.order||0)||a.name.localeCompare(b.name,'ru'))}
function bindProductControls(){$('productSearch').oninput=e=>{state.search=e.target.value;renderProducts()};$('productCategory').onchange=e=>{state.category=e.target.value;renderProducts()};$('productAdd').onclick=addProduct;$('productSelectVisible').onclick=()=>{visibleProducts().forEach(p=>state.selected.add(p.id));renderProducts()};$('productClearSelection').onclick=()=>{state.selected.clear();renderProducts()};$('productPrint').onclick=printSelectedProducts}
function renderProducts(){if(!document.getElementById('productList'))return;const cats=productCategories();const catEl=$('productCategory'),old=state.category;catEl.innerHTML='<option>Все</option>'+cats.map(c=>`<option>${esc(c)}</option>`).join('');catEl.value=cats.includes(old)?old:'Все';state.category=catEl.value;const arr=visibleProducts();$('productList').innerHTML=arr.map(p=>`<div class="product-row ${state.current===p.id?'active':''} ${p.active===false?'off':''}" data-id="${esc(p.id)}"><input class="product-select" type="checkbox" ${state.selected.has(p.id)?'checked':''}><div class="product-main"><b>${esc(p.name)}</b><small>${esc(p.category)}${p.country?' · '+esc(p.country):''}</small></div><div class="product-money"><small>${esc(p.portionLabel||'порция')}</small><b>${money(p.portionPrice)}</b></div><div class="product-money"><small>${esc(p.bottleVolume||'бутылка')}</small><b>${money(p.bottlePrice)}</b></div></div>`).join('')||'<div class="empty">Ничего не найдено</div>';$('productList').querySelectorAll('.product-row').forEach(row=>{row.onclick=e=>{const id=row.dataset.id;if(e.target.classList.contains('product-select')){e.stopPropagation();e.target.checked?state.selected.add(id):state.selected.delete(id);renderProductCount();return}state.current=id;renderProducts();renderProductEditor()}});renderProductCount();$('kProducts')&&($('kProducts').textContent=barProducts.length)}
function renderProductCount(){$('productSelectedCount').textContent=`Выбрано для печати: ${state.selected.size}`}
function renderProductEditor(){const p=barProducts.find(x=>x.id===state.current);if(!p)return;$('productEditor').innerHTML=`<div class="two"><div><label>Название</label><input id="pName" value="${esc(p.name)}"></div><div><label>Категория</label><input id="pCategory" value="${esc(p.category)}"></div></div><div class="two"><div><label>Страна / подпись</label><input id="pCountry" value="${esc(p.country||'')}"></div><div><label>Порядок</label><input id="pOrder" type="number" value="${esc(p.order||0)}"></div></div><div class="two"><div><label>Граммовка / порция</label><input id="pPortionLabel" value="${esc(p.portionLabel||'')}" placeholder="40 мл / 125 мл / 330 мл"></div><div><label>Цена порции, BYN</label><input id="pPortionPrice" type="number" step="0.01" value="${p.portionPrice??''}"></div></div><div class="two"><div><label>Объём бутылки</label><input id="pBottleVolume" value="${esc(p.bottleVolume||'')}" placeholder="700 мл / Бутылка"></div><div><label>Цена бутылки, BYN</label><input id="pBottlePrice" type="number" step="0.01" value="${p.bottlePrice??''}"></div></div><label>Комментарий</label><textarea id="pComment">${esc(p.comment||'')}</textarea><label style="display:flex;align-items:center;gap:8px"><input id="pActive" type="checkbox" style="width:auto" ${p.active!==false?'checked':''}>Показывать позицию</label><div class="actions" style="margin-top:18px"><button id="pSave" class="primary">Сохранить</button><button id="pDuplicate" class="ghost">Дублировать</button><button id="pArchive" class="danger">Архивировать</button></div>`;$('pSave').onclick=saveProduct;$('pDuplicate').onclick=()=>{const n={...p,id:'product-'+Date.now().toString(36),name:p.name+' — копия',order:Number(p.order||0)+1};barProducts.push(n);state.current=n.id;touchProducts();renderProducts();renderProductEditor()};$('pArchive').onclick=()=>{p.active=false;touchProducts();renderProducts();renderProductEditor()}}
function num(v){if(v===''||v==null)return null;const n=Number(v);return Number.isFinite(n)?n:null}
function saveProduct(){const p=barProducts.find(x=>x.id===state.current);if(!p)return;p.name=$('pName').value.trim();p.category=$('pCategory').value.trim()||'Прочее';p.country=$('pCountry').value.trim();p.order=Number($('pOrder').value)||0;p.portionLabel=$('pPortionLabel').value.trim();p.portionPrice=num($('pPortionPrice').value);p.bottleVolume=$('pBottleVolume').value.trim();p.bottlePrice=num($('pBottlePrice').value);p.comment=$('pComment').value.trim();p.active=$('pActive').checked;touchProducts();renderProducts();renderProductEditor();toast('Позиция сохранена локально')}
function addProduct(){const p={id:'product-'+Date.now().toString(36),category:'Прочее',name:'Новая позиция',country:'',portionLabel:'40 мл',portionPrice:null,bottleVolume:'',bottlePrice:null,active:true,order:999,comment:''};barProducts.push(p);state.current=p.id;touchProducts();renderProducts();renderProductEditor()}
function touchProducts(){window.barMenuDirty=true;markDirty();$('kProducts')&&($('kProducts').textContent=barProducts.length)}
function printSelectedProducts(){let arr=barProducts.filter(p=>state.selected.has(p.id)&&p.active!==false);if(!arr.length){toast('Выберите позиции для печати',true);return}arr.sort((a,b)=>productCategories().indexOf(a.category)-productCategories().indexOf(b.category)||Number(a.order||0)-Number(b.order||0));const groups=new Map();arr.forEach(p=>{if(!groups.has(p.category))groups.set(p.category,[]);groups.get(p.category).push(p)});const html=[...groups.entries()].map(([cat,items])=>`<section class="a4-category"><h2>${esc(cat)}</h2><table class="a4-table"><thead><tr><th>Наименование</th><th>Граммовка / порция</th><th>Цена, BYN</th><th>Объём бутылки</th><th>Бутылка, BYN</th></tr></thead><tbody>${items.map(p=>`<tr><td><b>${esc(p.name)}</b>${p.country?`<br><small>${esc(p.country)}</small>`:''}</td><td>${esc(p.portionLabel||'—')}</td><td class="num">${p.portionPrice==null?'—':esc(p.portionPrice)}</td><td>${esc(p.bottleVolume||'—')}</td><td class="num">${p.bottlePrice==null?'—':esc(p.bottlePrice)}</td></tr>`).join('')}</tbody></table></section>`).join('');$('productPrintRoot').innerHTML=`<main class="a4-products"><h1>BALI NIGHTCLUB · ПЕРЕЧЕНЬ БАРНОЙ ПРОДУКЦИИ</h1><div class="date">Цены указаны в белорусских рублях (BYN)</div>${html}<div class="a4-note">Сформировано в BALI COCKTAIL ADMIN · ${new Date().toLocaleDateString('ru-RU')}</div></main>`;setTimeout(()=>window.print(),120)}
window.ensureProducts=ensureProducts;window.renderProducts=renderProducts;window.defaultProducts=defaultProducts;window.addEventListener('DOMContentLoaded',ensureProducts);setTimeout(ensureProducts,0);
})();
