(() => {
  const S={selected:new Set(),search:'',category:'Все'};
  const safe=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  const products=()=>Array.isArray(window.barProducts)?window.barProducts:[];
  const money=v=>(v===null||v===undefined||v==='')?'—':new Intl.NumberFormat('ru-BY',{maximumFractionDigits:2}).format(Number(v))+' BYN';
  const categories=()=>['Все',...new Set(products().map(p=>p.category).filter(Boolean))];
  function visible(){const q=S.search.trim().toLowerCase();return products().filter(p=>p.active!==false&&(S.category==='Все'||p.category===S.category)&&(!q||(p.name||'').toLowerCase().includes(q)||(p.country||'').toLowerCase().includes(q))).sort((a,b)=>(a.category||'').localeCompare(b.category||'','ru')||Number(a.order||0)-Number(b.order||0)||(a.name||'').localeCompare(b.name||'','ru'));}
  function install(){
    if(document.getElementById('productsA4Styles'))return;
    const st=document.createElement('style');st.id='productsA4Styles';st.textContent=`
      .product-grid{grid-template-columns:minmax(520px,620px) minmax(520px,1fr)!important}.product-toolbar{grid-template-columns:minmax(300px,1fr) minmax(260px,340px)!important}.product-row{padding:12px!important}.product-row small{font-size:12px!important;line-height:1.4!important}.product-row b{font-size:14px!important}.product-a4-grid{display:grid;grid-template-columns:360px 1fr;gap:16px}.product-a4-row{display:grid;grid-template-columns:auto 1fr auto;gap:10px;align-items:center;padding:10px;border-bottom:1px solid var(--line)}.product-a4-row input{width:auto;margin:0}.product-a4-meta{font-size:12px;color:var(--muted);margin-top:3px}.product-a4-price{text-align:right;font-weight:800;white-space:nowrap}.product-a4-preview{background:#141418;border:1px solid var(--line);border-radius:16px;padding:16px;min-height:620px;overflow:auto}.a4-sheet{width:210mm;min-height:297mm;background:#fff;color:#111;padding:14mm 13mm;font-family:Arial,Helvetica,sans-serif;box-sizing:border-box}.a4-sheet h1{font-size:17pt;margin:0;text-align:center}.a4-sheet .sub{text-align:center;font-size:9pt;margin:1.5mm 0 6mm;color:#444}.a4-cat{font-size:11pt;font-weight:800;margin:4mm 0 1.5mm;border-bottom:.35mm solid #111;padding-bottom:1mm}.a4-table{width:100%;border-collapse:collapse;font-size:8.7pt}.a4-table th,.a4-table td{border-bottom:.18mm solid #c8c8c8;padding:1.6mm 1mm;vertical-align:top}.a4-table th{font-size:7.8pt;text-align:left;color:#444}.a4-table .num{text-align:right;white-space:nowrap}.a4-category-block{break-inside:avoid-page}.a4-footer{font-size:7pt;color:#666;margin-top:6mm;text-align:right}#productPrintRoot{display:none}
      @media(max-width:1050px){.product-grid,.product-a4-grid{grid-template-columns:1fr!important}.product-toolbar{grid-template-columns:1fr!important}}
      @media print{@page{size:A4 portrait;margin:0}body>*:not(#productPrintRoot){display:none!important}#productPrintRoot{display:block!important}.a4-sheet{margin:0;box-shadow:none;page-break-after:auto}}
    `;document.head.appendChild(st);
    const obs=new MutationObserver(()=>{document.querySelectorAll('.nav button').forEach(b=>{if(/меню\s*a3|генератор меню/i.test(b.textContent||''))b.style.display='none';});});obs.observe(document.body,{subtree:true,childList:true});
  }
  function ensureView(){install();const nav=document.querySelector('.nav'),main=document.querySelector('#app main');if(!nav||!main)return false;
    document.querySelectorAll('.nav button').forEach(b=>{if(/меню\s*a3|генератор меню/i.test(b.textContent||''))b.style.display='none';});
    if(!document.getElementById('productA4Nav')){const b=document.createElement('button');b.id='productA4Nav';b.textContent='Печать продукции A4';b.onclick=open;nav.appendChild(b)}
    if(!document.getElementById('productsA4')){const s=document.createElement('section');s.id='productsA4';s.className='view hidden';s.innerHTML=`<div class="top"><div><div class="title">Печать продукции A4</div><div class="muted">Выберите только нужные позиции. Цены отображаются в белорусских рублях.</div></div><div class="actions"><button id="pA4Print" class="primary">Печать / PDF</button></div></div><div class="product-a4-grid"><div class="card"><label>Поиск продукции</label><input id="pA4Search" class="search" placeholder="Название или страна"><label>Категория</label><select id="pA4Category"></select><div class="actions" style="margin:10px 0"><button id="pA4Visible" class="ghost">Выбрать видимые</button><button id="pA4All" class="ghost">Все активные</button><button id="pA4Clear" class="ghost">Снять</button></div><div id="pA4Count" class="muted"></div><div id="pA4List" style="max-height:560px;overflow:auto;margin-top:8px"></div></div><div class="card"><div class="section-title" style="margin-top:0">Предпросмотр A4</div><div id="pA4Preview" class="product-a4-preview"></div></div></div>`;main.appendChild(s);document.body.insertAdjacentHTML('beforeend','<div id="productPrintRoot"></div>');bind()}
    return true}
  function open(){if(!ensureView())return;document.querySelectorAll('.view').forEach(v=>v.classList.add('hidden'));document.getElementById('productsA4').classList.remove('hidden');document.querySelectorAll('.nav button').forEach(b=>b.classList.remove('active'));document.getElementById('productA4Nav').classList.add('active');render()}
  function bind(){document.getElementById('pA4Search').oninput=e=>{S.search=e.target.value;renderList()};document.getElementById('pA4Category').onchange=e=>{S.category=e.target.value;renderList()};document.getElementById('pA4Visible').onclick=()=>{visible().forEach(p=>S.selected.add(p.id));renderList()};document.getElementById('pA4All').onclick=()=>{products().filter(p=>p.active!==false).forEach(p=>S.selected.add(p.id));renderList()};document.getElementById('pA4Clear').onclick=()=>{S.selected.clear();renderList()};document.getElementById('pA4Print').onclick=()=>{const arr=products().filter(p=>S.selected.has(p.id)&&p.active!==false);if(!arr.length)return alert('Выберите позиции для печати');document.getElementById('productPrintRoot').innerHTML=sheet(arr);setTimeout(()=>window.print(),80)}}
  function rowMeta(p){const a=[];if(p.portionLabel)a.push(p.portionLabel);if(p.portionPrice!==null&&p.portionPrice!==undefined&&p.portionPrice!=='')a.push(money(p.portionPrice));if(p.bottleVolume)a.push('бут. '+p.bottleVolume);if(p.bottlePrice!==null&&p.bottlePrice!==undefined&&p.bottlePrice!=='')a.push('бут. '+money(p.bottlePrice));return a.join(' · ')}
  function render(){const sel=document.getElementById('pA4Category');sel.innerHTML=categories().map(c=>`<option ${c===S.category?'selected':''}>${safe(c)}</option>`).join('');renderList()}
  function renderList(){const el=document.getElementById('pA4List'),arr=visible();el.innerHTML=arr.map(p=>`<label class="product-a4-row"><input type="checkbox" data-id="${safe(p.id)}" ${S.selected.has(p.id)?'checked':''}><span><b>${safe(p.name)}</b><div class="product-a4-meta">${safe(p.category)}${p.country?' · '+safe(p.country):''}<br>${safe(rowMeta(p))}</div></span><span class="product-a4-price">${p.portionPrice!==null&&p.portionPrice!==undefined&&p.portionPrice!==''?money(p.portionPrice):money(p.bottlePrice)}</span></label>`).join('')||'<div class="empty">Ничего не найдено</div>';el.querySelectorAll('input').forEach(x=>x.onchange=()=>{x.checked?S.selected.add(x.dataset.id):S.selected.delete(x.dataset.id);renderPreview()});document.getElementById('pA4Count').textContent=`Выбрано: ${S.selected.size} · Показано: ${arr.length}`;renderPreview()}
  function group(arr){const m=new Map();arr.forEach(p=>{if(!m.has(p.category))m.set(p.category,[]);m.get(p.category).push(p)});return m}
  function sheet(arr){let html=`<div class="a4-sheet"><h1>BALI · БАРНАЯ ПРОДУКЦИЯ</h1><div class="sub">Прайс-лист · цены в белорусских рублях (BYN)</div>`;for(const [cat,ps] of group(arr)){html+=`<section class="a4-category-block"><div class="a4-cat">${safe(cat)}</div><table class="a4-table"><thead><tr><th>Наименование</th><th>Порция / объём</th><th class="num">Цена, BYN</th><th>Бутылка</th><th class="num">Цена бутылки, BYN</th></tr></thead><tbody>`+ps.map(p=>`<tr><td><b>${safe(p.name)}</b>${p.country?`<br><span style="color:#666;font-size:7.5pt">${safe(p.country)}</span>`:''}</td><td>${safe(p.portionLabel||'—')}</td><td class="num">${p.portionPrice===null||p.portionPrice===undefined||p.portionPrice===''?'—':safe(new Intl.NumberFormat('ru-BY',{maximumFractionDigits:2}).format(Number(p.portionPrice)))}</td><td>${safe(p.bottleVolume||'—')}</td><td class="num">${p.bottlePrice===null||p.bottlePrice===undefined||p.bottlePrice===''?'—':safe(new Intl.NumberFormat('ru-BY',{maximumFractionDigits:2}).format(Number(p.bottlePrice)))}</td></tr>`).join('')+`</tbody></table></section>`}return html+`<div class="a4-footer">BALI COCKTAIL · ${new Date().toLocaleDateString('ru-BY')}</div></div>`}
  function renderPreview(){const arr=products().filter(p=>S.selected.has(p.id)&&p.active!==false);document.getElementById('pA4Preview').innerHTML=arr.length?`<div style="transform:scale(.55);transform-origin:top center;height:635px">${sheet(arr.slice(0,Math.min(arr.length,28)))}</div>`:'<div class="empty">Выберите позиции для предпросмотра</div>'}
  window.openProductA4Print=open;install();setTimeout(ensureView,0);new MutationObserver(()=>ensureView()).observe(document.body,{childList:true,subtree:true});
})();